basePath: /api
definitions:
  er.ErrorOpenFile:
    description: Error parsing file info with filename, error and time
    properties:
      error:
        description: Error
      filename:
        description: File name
        type: string
      time:
        description: Time
        type: string
    type: object
  er.errorResponse:
    description: Error response
    properties:
      message:
        description: Error message
        type: string
    type: object
  unit.ProcessedFile:
    description: Processed file info
    properties:
      filepath:
        description: File path
        type: string
    type: object
  unit.Unit:
    description: Unit info with number, mqtt, invid, unitguid, with messageid, text,
      context, class, with level, area, addr, block, with type_, bit, invertbit
    properties:
      addr:
        description: Addr
        type: string
      area:
        description: Area
        type: string
      bit:
        description: Bit
      block:
        description: Block
      class:
        description: Class
        type: string
      context:
        description: Context
      invertbit:
        description: Invert bit
      invid:
        description: Invid
        type: string
      level:
        description: Level
        type: string
      messageid:
        description: Message ID
        type: string
      mqtt:
        description: MQTT
      number:
        description: Unit number
        type: string
      text:
        description: Text
        type: string
      type_:
        description: Type
      unitguid:
        description: Unit GUID
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: zhiborkin_ei@mail.ru
    name: Evgenii Zhiborkin
    url: https://t.me/zyltrcuj
  description: API Server for parsing files and getting data from MongoDB
  title: File Parser API
  version: "1.0"
paths:
  /errorsdata:
    get:
      description: Get errors data based on filename with pagination
      parameters:
      - description: File name to filter errors
        in: query
        name: filename
        required: true
        type: string
      - description: Page number for pagination (default is 1)
        in: query
        name: page
        type: integer
      - description: Number of items to show per page (default is 10)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/er.ErrorOpenFile'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.errorResponse'
      summary: Get errors data
      tags:
      - APIs
  /processeddata:
    get:
      description: Get processed data based on unit GUID with pagination
      parameters:
      - description: Unit GUID to filter processed data
        in: query
        name: unit_guid
        required: true
        type: string
      - description: Page number for pagination (default is 1)
        in: query
        name: page
        type: integer
      - description: Number of items to show per page (default is 10)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/unit.Unit'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.errorResponse'
      summary: Get processed data
      tags:
      - APIs
  /processedfiles:
    get:
      description: Get processed files with pagination
      parameters:
      - description: Page number for pagination (default is 1)
        in: query
        name: page
        type: integer
      - description: Number of items to show per page (default is 10)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/unit.ProcessedFile'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.errorResponse'
      summary: Get processed files
      tags:
      - APIs
swagger: "2.0"
